### ISSUE TITLE
AccessDenied error from pskolibri module

### ISSUE THREAD

**Issue by kollivier** [learningequality/kolibri-installer-android#28]
Check into why we're receiving this error, and why it only appears to trigger on some devices. Traceback:

11-08 13:27:20.720 20897 30263 W AbstractXMPPConnection: java.security.cert.CertificateException: Hostname verification of certificate failed. Certificate does not authenticate learningequality.org
11-08 13:27:21.609 30166 30234 I python  : INFO:root:Starting server...
11-08 13:27:21.706 30166 30234 I python  : ERROR:root:Traceback (most recent call last):
11-08 13:27:21.706 30166 30234 I python  :   File "/data/user/0/org.learningequality.Kolibri/files/pew/kivy_pew/webview.py", line 49, in run
11-08 13:27:21.706 30166 30234 I python  :     super(PEWThread, self).run()
11-08 13:27:21.706 30166 30234 I python  :   File "/data/user/0/org.learningequality.Kolibri/files/lib/python2.7/site-packages/jnius/__init__.py", line 53, in jnius_thread_hook
11-08 13:27:21.706 30166 30234 I python  :     return orig_thread_run(*args, **kwargs)
11-08 13:27:21.706 30166 30234 I python  :   File "/home/kivy/.local/share/python-for-android/build/other_builds/python2-openssl-sqlite3/armeabi/python2/python-install/lib/python2.7/threading.py", line 505, in run
11-08 13:27:21.706 30166 30234 I python  :   File "main.py", line 67, in start_django
11-08 13:27:21.706 30166 30234 I python  :     run_server(5000)
11-08 13:27:21.706 30166 30234 I python  :   File "/data/user/0/org.learningequality.Kolibri/files/kolibri/utils/server.py", line 158, in run_server
11-08 13:27:21.706 30166 30234 I python  :     from kolibri.deployment.default.wsgi import application
11-08 13:27:21.706 30166 30234 I python  :   File "/data/user/0/org.learningequality.Kolibri/files/kolibri/deployment/default/wsgi.py", line 15, in <module>
11-08 13:27:21.706 30166 30234 I python  :     application = get_wsgi_application()
11-08 13:27:21.706 30166 30234 I python  :   File "/data/data/org.learningequality.Kolibri/files/kolibri/dist/django/core/wsgi.py", line 14, in get_wsgi_application
11-08 13:27:21.706 30166 30234 I python  :     return WSGIHandler()
11-08 13:27:21.707 30166 30234 I python  :   File "/data/data/org.learningequality.Kolibri/files/kolibri/dist/django/core/handlers/wsgi.py", line 151, in __init__
11-08 13:27:21.707 30166 30234 I python  :     self.load_middleware()
11-08 13:27:21.707 30166 30234 I python  :   File "/data/data/org.learningequality.Kolibri/files/kolibri/dist/django/core/handlers/base.py", line 80, in load_middleware
11-08 13:27:21.707 30166 30234 I python  :     middleware = import_string(middleware_path)
11-08 13:27:21.707 30166 30234 I python  :   File "/data/data/org.learningequality.Kolibri/files/kolibri/dist/django/utils/module_loading.py", line 20, in import_string
11-08 13:27:21.707 30166 30234 I python  :     module = import_module(module_path)
11-08 13:27:21.707 30166 30234 I python  :   File "/home/kivy/.local/share/python-for-android/build/other_builds/python2-openssl-sqlite3/armeabi/python2/python-install/lib/python2.7/importlib/__init__.py", line 37, in import_module
11-08 13:27:21.707 30166 30234 I python  :     __import__(name)
11-08 13:27:21.707 30166 30234 I python  :   File "/data/user/0/org.learningequality.Kolibri/files/kolibri/core/analytics/middleware.py", line 24, in <module>
11-08 13:27:21.707 30166 30234 I python  :     kolibri_process = psutil.Process()
11-08 13:27:21.707 30166 30234 I python  :   File "/data/user/0/org.learningequality.Kolibri/files/kolibri/core/analytics/pskolibri/__init__.py", line 225, in __init__
11-08 13:27:21.707 30166 30234 I python  :     self._init(pid)
11-08 13:27:21.707 30166 30234 I python  :   File "/data/user/0/org.learningequality.Kolibri/files/kolibri/core/analytics/pskolibri/__init__.py", line 246, in _init
11-08 13:27:21.707 30166 30234 I python  :     self.create_time()
11-08 13:27:21.707 30166 30234 I python  :   File "/data/user/0/org.learningequality.Kolibri/files/kolibri/core/analytics/pskolibri/__init__.py", line 273, in create_time
11-08 13:27:21.707 30166 30234 I python  :     self._create_time = self._proc.create_time()
11-08 13:27:21.707 30166 30234 I python  :   File "/data/user/0/org.learningequality.Kolibri/files/kolibri/core/analytics/pskolibri/_pslinux.py", line 170, in wrapper
11-08 13:27:21.707 30166 30234 I python  :     raise AccessDenied()
11-08 13:27:21.707 30166 30234 I python  : AccessDenied
11-08 13:27:21.707 30166 30234 I python  : 
11-08 13:27:22.388 30166 30237 I python  : INFO:root:Kolibri server not yet started, checking again in one second...
11-08 13:27:24.412 30166 30237 I python  : INFO:root:Kolibri server not yet started, checking again in one second...
11-08 13:27:26.430 30166 30237 I python  : INFO:root:Kolibri server not yet started, checking again in one second...

**Comment by kollivier** [comment]
Looks like /proc access was restricted in newer Android versions. Suggested workaround is to use Android APIs instead:

https://stackoverflow.com/questions/39092139/how-to-traversed-proc-directory-in-android-in-apk
